"""
GC: Dead code detection (Phase 6).
Uses vulture to find unused code in src/ and generates CLEANUP_NEEDED.md.
Does NOT delete anything — outputs a review list for human/Agent decision.
Run monthly.
Requires: pip install vulture
"""
import subprocess
import sys
import pathlib
from datetime import date


def main():
    try:
        subprocess.run(["vulture", "--version"], capture_output=True, check=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("vulture not found. Install with: pip install vulture")
        sys.exit(1)

    src_dir = pathlib.Path("src")
    if not src_dir.exists():
        print("src/ not found — skipping dead code check")
        sys.exit(0)

    result = subprocess.run(
        [
            "vulture", "src/",
            "--min-confidence", "80",
            "--exclude", "src/tests/",
        ],
        capture_output=True, text=True
    )

    if result.stdout.strip():
        output_path = pathlib.Path("CLEANUP_NEEDED.md")
        content = f"""# Dead Code Cleanup Needed

Generated by `scripts/gc_dead_code.py` on {date.today().isoformat()}.
Minimum confidence: 80%.

Review each item below. If confirmed unused, delete it.
If it is still needed, add it to vulture's whitelist (`vulture_whitelist.py`).

```
{result.stdout}
```

## Instructions for Agent
1. For each item, check git blame and recent usage before deleting.
2. If deleting: remove the dead code and the corresponding tests (if any).
3. If keeping: add to `vulture_whitelist.py` with a comment explaining why.
4. After cleanup, re-run this script to verify the list shrinks.
"""
        output_path.write_text(content, encoding="utf-8")
        print(f"⚠️  Potential dead code found. Review list saved to: {output_path}")
        print(result.stdout)
    else:
        print("✅ No dead code found (confidence >= 80%)")
        cleanup = pathlib.Path("CLEANUP_NEEDED.md")
        if cleanup.exists():
            cleanup.unlink()
            print("   (Removed stale CLEANUP_NEEDED.md)")


if __name__ == "__main__":
    main()
